version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: moukhit/frontend
    ports:
      - '5001:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: moukhit/frontend_tests
    volumes:
      - /app/node_modules
      - .:/app
    command: ['yarn', 'test']
